import Navbar from './components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import Sidebar from "./components/Sidebar";

import Header from './components/Header';
import { createServerComponentClient } from '@supabase/auth-helpers-nextjs'
import CryptoList from "./components/CryptoList";


const inter = Inter({ subsets: ['latin'], weight: ['400', '700'] });

export const dynamic = 'force-dynamic'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex items-start justify-between`} >
        <CryptoList/>
        <main className='w-full h-full'>
          {/* <Header/> */}
          {children}
        </main>
      </body>
    </html>
  )
}
